name: Workflow

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: slack - GitHub Actions Slack integration
        # You may pin to the exact commit or the version.
        # uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d
        uses: act10ns/slack@v2.1.0
        with:
          # Specify Slack Incoming Webhook URL
          webhook-url: https://hooks.slack.com/services/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 # optional
          # Configuration file
          # config: # optional, default is .github/slack.yml
          # Specify success, failure, cancelled or a custom status
          # status: 
          # Report on the status of individual steps
          # steps: # optional
          # matrix properties
          # matrix: # optional
          # Override default channel with different channel or username
          channel: testing # optional
          # Override message format for step
          message: testing # optional
